import { ButtonGroup } from "@trussworks/react-uswds"
import Head from "next/head"
import LinkButton from "../components/link-button"
import Hero from "../content/representantes/hero"

const ModeButton = ({ condition, primaryText, secondaryText, href }) =>
    <LinkButton
        className={condition ? "" : "usa-button--outline"}
        aria-label={condition ? "" : undefined}
        {...{ href }}
    >
        {condition ? primaryText : secondaryText}
    </LinkButton>

const Layout = ({ mapa = false, children }) =>
    <div>
        <Head>
            <title>Representantes | Cabilde</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <section id="test-section-id" className="usa-section usa-section--light">
            <Hero />
            <ButtonGroup type="segmented">
                {/* TODO: make screen reader indicate current view, otherwise indicated by button style */}
                <ModeButton
                    primaryText="Tabla"
                    secondaryText="Cambia a la tabla"
                    condition={!mapa}
                    href="/representantes"
                />
                <ModeButton
                    primaryText="Mapa"
                    secondaryText="Cambia al mapa"
                    condition={mapa}
                    href="/representantes/mapa"
                />
            </ButtonGroup>
        </section>
        {children}
    </div>
    
export default Layout
