import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.scss"
import Link from "../components/link"
import Hero from "../content/home/hero.mdx"
import GobiernoAbierto from "../content/home/gobierno-abierto.mdx"
import EducacionCivica from "../content/home/educacion-civica.mdx"
import Representantes from "../content/home/representantes.mdx"
import Iniciativas from "../content/home/iniciativas.mdx"
import Boletin from "../content/home/boletin.mdx"
import EsteSitio from "../content/home/este-sitio.mdx"
import { Grid, GridContainer } from "@trussworks/react-uswds"
import GridLink from "../components/grid-link"
import LinkButton from "../components/link-button"

const Home = () =>
  <>
    <Head>
      <title>Cabilde</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <section id="test-section-id" className="usa-section usa-section--dark">
        <Hero />
        <LinkButton href="./mensaje" size="big">
          Comienza
        </LinkButton>
      </section>
      <GridContainer>
        <Grid row>
          <GridLink href="./gobierno-abierto">
            <GobiernoAbierto />
          </GridLink>
          <GridLink href="./educacion-civica">
            <EducacionCivica />
          </GridLink>
        </Grid>
        <Grid row>
          <GridLink href="./representantes">
            <Representantes />
          </GridLink>
          <GridLink href="./iniciativas">
            <Iniciativas />
          </GridLink>
        </Grid>
      </GridContainer>
      <GridContainer>
        <Grid row>
          <Grid tablet={{ col: true }}>
            <EsteSitio />
            <LinkButton href="./conocenos" size="big">
              Conócenos
            </LinkButton>
          </Grid>
          <Grid tablet={{ col: true }}>
            <Boletin />
            <LinkButton href="#" size="big">
              Suscríbeme
            </LinkButton>
          </Grid>
        </Grid>
      </GridContainer>
    </main>
  </>

export default Home
