import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.scss"
import Link from "../components/link"
import Hero from "../content/home/hero.mdx"
 
const Home = () =>
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <section id="test-section-id" className="usa-section usa-section--dark">
        <Hero />
        <Link className="usa-button usa-button--big"
          variant="unstyled"
          href="./mensaje">
          Comenzar
        </Link>
      </section>
    </main>
  </>

export default Home
